Basic jwt-based security was implemented
olyaklipa/remind-me pull request #6
Opened 2023-09-18 10:52 UTC by olyaklipa

Currently without refresh token. Dependency used: java-jwt.

2023-09-26 09:22 UTC, pauldaniv commented on src/main/java/olya/app/remindme/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("User " + email + " not found"));
Throw `NotFoundException` instead

2023-09-26 09:28 UTC, pauldaniv commented on src/main/java/olya/app/remindme/model/LoginRequest.java
> +public class LoginRequest {
Add validation

2023-09-26 09:29 UTC, pauldaniv commented on src/main/java/olya/app/remindme/model/LoginRequest.java
> +    private String password;
Add `@Size` validation

2023-09-26 09:29 UTC, pauldaniv commented on src/main/java/olya/app/remindme/model/LoginRequest.java
> +    private String email;
Add `@Email` or `@Pattern` validation

2023-09-26 09:30 UTC, pauldaniv commented on src/main/java/olya/app/remindme/controller/AuthController.java
> +    public LoginResponse login(@RequestBody LoginRequest loginRequest){
Add `@Valid` annotation

2023-09-26 09:34 UTC, pauldaniv commented on src/main/java/olya/app/remindme/security/JwtAuthenticationFilter.java
> +           return Optional.of(token.substring(7));
Avoid magic numbers. Put `Bearer ` into a field and use it's length

2023-09-26 09:41 UTC, pauldaniv commented on src/main/java/olya/app/remindme/security/JwtDecoder.java
> +    public DecodedJWT decode(String token) {
Rename to `decodeAndVerify`

2023-09-26 09:45 UTC, pauldaniv commented on src/main/java/olya/app/remindme/security/JwtToPrincipalConverter.java
> +        if (claim.isNull() || claim.isMissing()) {
Fetch Authorities from database instead of jwt token

2023-09-26 09:47 UTC, pauldaniv commented on src/main/java/olya/app/remindme/security/JwtToPrincipalConverter.java
> +                .authorities(extractAuthorities(jwt))
Don't store authorities in the token

2023-09-26 10:02 UTC, pauldaniv commented on src/main/resources/application.properties
> +security.jwt.secret-key=remindmesecretkey
Use ENV variable and default value 
```suggestion
security.jwt.secret-key=${JWT_SECRET_KEY:<default_key>}
```

2023-09-26 10:03 UTC, pauldaniv requested changes
Added a few minor comments

2023-10-08 20:18 UTC, olyaklipa commented on src/main/java/olya/app/remindme/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("User " + email + " not found"));
NotFoundException: I have a question here (will ask on Tuesday)

2023-10-09 18:07 UTC, pauldaniv approved these changes

2023-11-20 13:59 UTC, merged